#ifndef QOBJECTLISTMODEL_GLOBAL_H
#define QOBJECTLISTMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QOBJECTLISTMODEL_LIBRARY)
#  define QOBJECTLISTMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QOBJECTLISTMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QOBJECTLISTMODEL_GLOBAL_H
